import type { CustomerType, ProductType } from "@/types/auth"
import type { Menu, MenuType } from "@/types/menu"
import {
  Bell,
  FileText,
  Hamburger,
  House,
  LayoutDashboard,
  SendHorizontal,
  Settings,
  User,
} from "lucide-react"

export const initialProducts: ProductType[] = [
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Classic Burger",
    category: "Fast Food",
    productunit: 1,
    price: 1500,
    quantity: 45,
    status: "In Stock",
    description: "Steak haché, cheddar, salade, tomate",
    image: "/images/Classic Burger.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Chicken Burger",
    category: "Fast Food",
    productunit: 3,
    price: 1500,
    quantity: 42,
    status: "In Stock",
    description: "Poulet croustillant, mayo, cornichons",
    image: "/images/Chicken Burger.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Double Smash",
    category: "Fast Food",
    productunit: 2,
    price: 2500,
    quantity: 50,
    status: "In Stock",
    description: "Double steak, double cheddar, sauce spéciale",
    image: "/images/Double Smash.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Hot Dog",
    category: "Fast Food",
    productunit: 4,
    price: 2000,
    quantity: 40,
    status: "In Stock",
    description: "Saucisse grillée, moutarde, ketchup",
    image: "/images/Hot Dog.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Pizza Margherita",
    category: "Fast Food",
    productunit: 1,
    price: 4000,
    quantity: 47,
    status: "In Stock",
    description: "Mozzarella, tomate, basilic frais",
    image: "/images/Pizza Margherita.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Tacos Poulet",
    category: "Fast Food",
    productunit: 2,
    price: 2500,
    quantity: 43,
    status: "In Stock",
    description: "Poulet grillé, fromage fondu, frites",
    image: "/images/Tacos Poulet.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Nuggets x8",
    category: "Fast Food",
    productunit: 4,
    price: 2500,
    quantity: 41,
    status: "In Stock",
    description: "Nuggets croustillants, sauce BBQ",
    image: "/images/Nuggets x8.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "French Fries",
     category: "Fast Food",
    productunit: 1,
    price: 1500,
    quantity: 46,
    status: "In Stock",
    description: "Frites dorées, sel, ketchup",
    image: "/images/French Fries.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Cheese Sandwich",
    category: "Fast Food",
    productunit: 2,
    price: 2000,
    quantity: 38,
    status: "In Stock",
    description: "Pain grillé, cheddar fondu, jambon",
    image: "/images/Cheese Sandwich.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Gâteau Au Chocolat",
    category: "Pâtiserie",
    productunit: 2,
    price: 2000,
    quantity: 38,
    status: "In Stock",
    description: "Pain grillé, cheddar fondu, jambon",
    image: "/images/Gâteau Au Chocolat.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Jus Locaux",
    category: "Fast Food",
    productunit: 2,
    price: 2000,
    quantity: 38,
    status: "In Stock",
    description: "Pain grillé, cheddar fondu, jambon",
    image: "/images/Jus Locaux.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Recette Vermicelle",
    category: "Restaurant",
    productunit: 2,
    price: 2000,
    quantity: 38,
    status: "In Stock",
    description: "Vermicelle, Poulet, Sauce",
    image: "/images/Recette Vermicelle.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Un dibi poulet",
    category: "Fast Food",
    productunit: 2,
    price: 4000,
    quantity: 38,
    status: "In Stock",
    description: "Poulet, Oignon",
    image: "/images/Un dibi poulet.jpg",
  },
  {
    productid: `ID-${crypto.randomUUID()}`,
    productname: "Glace",
    category: "Glacier",
    productunit: 2,
    price: 1500,
    quantity: 38,
    status: "In Stock",
    description: " ",
    image: "/images/Glace.jpg",
  },
]

export const menu: MenuType[] = [
  {
    name: "Dashboard",
    link: "/dashboard",
    icon: House,
  },
  {
    name: "Gestion des Menus",
    link: "/dashboard/menus",
    icon: LayoutDashboard,
  },
  {
    name: "Ventes",
    link: "/dashboard/sales",
    icon: FileText,
  },
  {
    name: "Gestion des Produits",
    link: "/dashboard/product",
    icon: Hamburger,
  },
  {
    name: "Notifications",
    link: "/dashboard/notifications",
    icon: Bell,
  },
  {
    name: "Gestion clientèle",
    link: "/dashboard/customers-page",
    icon: User,
  },
  {
    name: "Historique des commandes",
    link: "/dashboard/history",
    icon: SendHorizontal,
  },
  {
    name: "Paramètres",
    link: "/dashboard/settings",
    icon: Settings,
  },
]

export const initialCustomers: CustomerType[] = [
  {
    id: 1,
    name: "SIMEON DAISE",
    orders: 150,
    gender: "Male",
    spent: "1500 FCFA",
    address: "Castor",
    image: "/images/SIMEON DAISE.jpg"
  },
   {
     id: 2,
    name: "Jonas",
    orders: 250,
    gender: "Male",
    spent: "2000 FCFA",
    address: "Pikine",
    image: "/images/Jonas.jpg"
  },
   {
     id: 3,
    name: "Caleb Vogel",
    orders: 200,
    gender: "Male",
    spent: "2500 FCFA",
    address: "Medina",
    image: "/images/Caleb Vogel.jpg"
  },
   {
     id: 4,
    name: "THEODOR",
    orders: 350,
    gender: "Male",
    spent: "2900 FCFA",
    address: "Guediawaye",
    image: "/images/Theodor.jpg"
  },
   {
     id: 5,
    name: "JACK JEAN",
    orders: 450,
    gender: "Male",
    spent: "3500 FCFA",
    address: "Thiaroy",
    image: "/images/Jack Jean.jpg"
  },
   {
     id: 6,
    name: "LEONARD",
    orders: 360,
    gender: "Male",
    spent: "3800 FCFA",
    address: "Rufisque",
    image: "/images/Leonard.jpg"
  },
   {
     id: 7,
    name: "FRANCOIS",
    orders: 250,
    gender: "Male",
    spent: "3000 FCFA",
    address: "Mbao",
    image: "/images/François.jpg"
  },
   {
     id: 8,
    name: "ADRIEN",
    orders: 380,
    gender: "Male",
    spent: "2500 FCFA",
    address: "Grand Mbao",
    image: "/images/Adrien.jpg"
  },
   {
     id: 9,
    name: "YANICK",
    orders: 470,
    gender: "Male",
    spent: "3300 FCFA",
    address: "Castor",
    image: "/images/Yanick.jpg"
  },
   {
     id: 9,
    name: "YANICK",
    orders: 470,
    gender: "Male",
    spent: "3300 FCFA",
    address: "Castor",
    image: "/images/Yanick.jpg"
  },
   {
     id: 9,
    name: "YANICK",
    orders: 470,
    gender: "Male",
    spent: "3300 FCFA",
    address: "Castor",
    image: "/images/Yanick.jpg"
  },
   {
     id: 9,
    name: "YANICK",
    orders: 470,
    gender: "Male",
    spent: "3300 FCFA",
    address: "Castor",
    image: "/images/Yanick.jpg"
  },
   {
     id: 9,
    name: "YANICK",
    orders: 470,
    gender: "Male",
    spent: "3300 FCFA",
    address: "Castor",
    image: "/images/Yanick.jpg"
  },
   {
     id: 9,
    name: "YANICK",
    orders: 470,
    gender: "Male",
    spent: "3300 FCFA",
    address: "Castor",
    image: "/images/Yanick.jpg"
  }
]



  export const slideImages: string[] = [
    "/images/patrimoine-culinaire.jpeg",
    "/images/bg-1.jpeg",
    "/images/bg-2.jpeg",
  ]

  export const menus: Menu[] = [
    {
      id: 1,
      nom: "Classic Burger",
      prix: 1500,
      note: 4.5,
      description: "Steak haché, cheddar, salade, tomate",
      image: "/images/Classic Burger.jpeg",
    },
    {
      id: 2,
      nom: "Chicken Burger",
      prix: 1800,
      note: 4.2,
      description: "Poulet croustillant, mayo, cornichons",
      image: "/images/Chicken Burger.jpeg",
    },
    {
      id: 3,
      nom: "Double Smash",
      prix: 2500,
      note: 5.0,
      description: "Double steak, double cheddar, sauce spéciale",
      image: "/images/Double Smash.jpeg",
    },
    {
      id: 4,
      nom: "Hot Dog",
      prix: 2000,
      note: 4.0,
      description: "Saucisse grillée, moutarde, ketchup",
      image: "/images/Hot Dog.jpeg",
    },
    {
      id: 5,
      nom: "Pizza Margherita",
      prix: 4000,
      note: 4.7,
      description: "Mozzarella, tomate, basilic frais",
      image: "/images/Pizza Margherita.jpeg",
    },
    {
      id: 6,
      nom: "Tacos Poulet",
      prix: 2500,
      note: 4.3,
      description: "Poulet grillé, fromage fondu, frites",
      image: "/images/Tacos Poulet.jpeg",
    },
    {
      id: 7,
      nom: "Nuggets x8",
      prix: 2500,
      note: 4.1,
      description: "Nuggets croustillants, sauce BBQ",
      image: "/images/Nuggets x8.jpeg",
    },
    {
      id: 8,
      nom: "French Fries",
      prix: 1500,
      note: 4.6,
      description: "Frites dorées, sel, ketchup",
      image: "/images/French Fries.jpeg",
    },
    {
      id: 9,
      nom: "Cheese Sandwich",
      prix: 2000,
      note: 3.8,
      description: "Pain grillé, cheddar fondu, jambon",
      image: "/images/Cheese Sandwich.jpeg",
    },
  ]
