import type { Menu } from "@/types/menu";

export const menus: Menu[] = [
    {
      id: 1,
      nom: "Classic Burger",
      prix: 1500,
      note: 4.5,
      description: "Steak haché, cheddar, salade, tomate",
      image: "/images/Classic Burger.jpeg",
    },
    {
      id: 2,
      nom: "Wrap Poulet",
      prix: 2800,
      note: 4.1,
      description: "Poulet grillé, légumes, sauce yaourt",
      image: "/images/Wrap Poulet.jpeg",
    },
    {
      id: 3,
      nom: "Chicken Burger",
      prix: 1800,
      note: 4.2,
      description: "Poulet croustillant, mayo, cornichons",
      image: "/images/Chicken Burger.jpeg",
    },
    {
      id: 4,
      nom: "Double Smash",
      prix: 2500,
      note: 5.0,
      description: "Double steak, double cheddar, sauce spéciale",
      image: "/images/Double Smash.jpeg",
    },
    {
      id: 5,
      nom: "Waffle",
      prix: 2500,
      note: 4.5,
      description: "Gaufre croustillante, chantilly",
      image: "/images/Waffle.jpeg",
    },
    {
      id: 6,
      nom: "Hot Dog",
      prix: 2000,
      note: 4.0,
      description: "Saucisse grillée, moutarde, ketchup",
      image: "/images/Hot Dog.jpeg",
    },
    {
      id: 7,
      nom: "Jus d'Orange",
      prix: 1000,
      note: 4.1,
      description: "Jus d'orange frais pressé",
      image: "/images/Jus d'Orange.jpeg",
    },
    {
      id: 8,
      nom: "Pizza Margherita",
      prix: 4000,
      note: 4.7,
      description: "Mozzarella, tomate, basilic frais",
      image: "/images/Pizza Margherita.jpeg",
    },
    {
      id: 9,
      nom: "Veggie Burger",
      prix: 2500,
      note: 4.0,
      description: "Steak végétal, avocat, salade",
      image: "/images/Veggie Burger.jpeg",
    },
    {
      id: 10,
      nom: "Tacos Poulet",
      prix: 2500,
      note: 4.3,
      description: "Poulet grillé, fromage fondu, frites",
      image: "/images/Tacos Poulet.jpeg",
    },
    {
      id: 11,
      nom: "Nuggets x8",
      prix: 2500,
      note: 4.1,
      description: "Nuggets croustillants, sauce BBQ",
      image: "/images/Nuggets x8.jpeg",
    },
    {
      id: 12,
      nom: "French Fries",
      prix: 1500,
      note: 4.6,
      description: "Frites dorées, sel, ketchup",
      image: "/images/French Fries.jpeg",
    },
    {
      id: 13,
      nom: "Onion Rings",
      prix: 1500,
      note: 4.4,
      description: "Rondelles d'oignon croustillantes",
      image: "/images/Onion Rings.jpeg",
    },
    {
      id: 14,
      nom: "Cheese Sandwich",
      prix: 2000,
      note: 3.8,
      description: "Pain grillé, cheddar fondu, jambon",
      image: "/images/Cheese Sandwich.jpeg",
    },
    {
      id: 15,
      nom: "Sundae Chocolat",
      prix: 1800,
      note: 4.6,
      description: "Glace vanille, sauce chocolat",
      image: "/images/Sundae Chocolat.jpeg",
    },
      {
      id: 16,
      nom: "Pancakes",
      prix: 2500,
      note: 4.6,
      description: "Pancakes moelleux, sirop d'érable",
      image: "/images/Pancakes.jpeg",
    },
    {
      id: 17,
      nom: "BBQ Burger",
      prix: 3000,
      note: 4.3,
      description: "Burger au barbecue, cheddar, oignons caramélisés",
      image: "/images/BBQ Burger.jpeg",
    },
     {
      id: 18,
      nom: "Apple Pie",
      prix: 2000,
      note: 4.4,
      description: "Tarte aux pommes, glaçage",
      image: "/images/Apple Pie.jpeg",
    },
    {
      id: 19,
      nom: "Milkshake Vanille",
      prix: 2000,
      note: 4.7,
      description: "Milkshake à la vanille, crème glacée",
      image: "/images/Milkshake Vanille.jpeg",
    },
     {
      id: 20,
      nom: "Fish Burger",
      prix: 2500,
      note: 4.6,
      description: "Poisson pané, laitue, tomate",
      image: "/images/Fish Burger.jpeg",
    },
    {
      id: 21,
      nom: "Coca Cola",
      prix: 1000,
      note: 4.5,
      description: "Boisson gazeuse, sucrée",
      image: "/images/Coca Cola.jpeg",
    },
    {
      id: 22,
      nom: "Churros",
      prix: 1500,
      note: 4.7,
      description: "Beignets croustillants, sucre en poudre",
      image: "/images/Churros.jpeg",
    },
    {
      id: 23,
      nom: "Burrito",
      prix: 3500,
      note: 4.3,
      description: "Tortilla remplie de viande, légumes et sauces",
      image: "/images/Burrito.jpeg",
    },
      {
      id: 24,
      nom: "Milkshake Chocolat",
      prix: 2000,
      note: 4.7,
      description: "Milkshake à la vanille, crème glacée",
      image: "/images/Milkshake Chocolat.jpeg",
    },
     {
      id: 25,
      nom: "Quesadilla",
      prix: 3000,
      note: 4.4,
      description: "Tortilla remplie de fromage et de viande",
      image: "/images/Quesadilla.jpeg",
    },
    {
      id: 26,
      nom: "Club Sandwich",
      prix: 2800,
      note: 4.5,
      description: "Jambon, fromage, salade, tomate",
      image: "/images/Club Sandwich.jpeg",
    },
    {
      id: 27,
      nom: "Donut",
      prix: 1000,
      note: 4.2,
      description: "Beignet glacé au chocolat",
      image: "/images/Donut.jpeg",
    },
  ]